---
- name: Copy template
  template:
    src: proxy_template.conf.j2
    dest: /etc/nginx/sites-available/{{ site_name_proxy }}.conf
    mode: 0644

- name: Enable site {{ site_name_proxy }}
  file:
    src: /etc/nginx/sites-available/{{ site_name_proxy }}.conf
    dest: /etc/nginx/sites-enabled/{{ site_name_proxy }}.conf
    state: link
  notify: reload nginx