---
- name: Install Nginx
  apt: name=nginx state=present

- name: Change log format
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^access_log'
    insertbefore: log_format main '$http_x_forwarded_for - $remote_user [$time_local] "$host" "$request" '
            '$status $body_bytes_sent "$http_referer" '
            '"$http_user_agent" $request_time';
    line: access_log /var/log/nginx/access.log main;