---
- hosts: ceph
  become: yes
  pre_tasks:
    - name: Update & Upgrade APT repository
      apt:
        update_cache: yes
    - name: test
      debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

  roles:
    - githubixx.ansible_role_wireguard
    - ceph