---
- name: Install nftables
  apt: name=nftables state=present

- name: Install configuration from template
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: 0644
  notify: 
    - restart nftables